global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: playground-golang
    static_configs:
      - targets: ['playground-golang:3030']
  - job_name: playground-golang-2
    static_configs:
      - targets: ['playground-golang-2:3031']